---
title: "PCV_analysis -- Dataset 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load required R packages
```{r}
library(table1)
library(dplyr)
library(ggplot2)
#library(GGally)
library(car)
```

```{r}
### Load the data: 
supp_table <- read.csv("~/Documents/Ottavia/Data_pharma/suppl_table_filled.csv")
```

## Check that individuals are the same across dataframes
```{r}
print(paste0("Total number of individuals: "))
sum(supp_table$count)
```
## Define covariates
```{r}
list_cov <- c("year_month","age","patient_gender_code","race_code","PCV_combined") #removed "income_est_mod"
## drop covariates
drop.cols <- c("bmi_30_plus","income_est_mod")
df_table <- supp_table %>% select(-all_of(drop.cols))
```
## Run the first logistic regression analysis looking at outcome: severe respiratory outcome for Covid-19 versus non-severe outcomes
```{r}
list_out <- c("non_severe","resp_severe")
m1<-run_model(df_table,list_cov,list_out)
View(m1$m.table)
```